export const featuredTripData = [
  { id: 1,
    image: "https://i.postimg.cc/L4JmG0V6/2-Classic-Polar-Bear-Adventure.jpg",
    title: "Classic Polar Bear Adventure",
    details: `Meet the "King of the Arctic!" Our flagship polar bear tour is an expertly guided small-group adventure to see the world's largest concentration of polar bears in their tundra habitat along Hudson Bay.`,
    timeline: `6 or 7 Days / Oct & Nov, From $6795 (+air)`,
    addon: false,
    additionalDetails: null
  },
  { id: 2,
    image: "https://i.postimg.cc/j5mYsthq/Northern-Lights-hero.jpg",
    title: "Northern Lights & Arctic Cultures",
    details: `Churchill, Manitoba is one of the best places on the planet to view the aurora borealis — see it in comfort from our exclusive Aurora Pod featuring a 360-degree view of the night sky.`,
    timeline: `7 Days / Jan – Mar, From $5995 (+air)`,
    addon: false,
    additionalDetails: null
  },
  { id: 3,
    image: "https://i.postimg.cc/G36bRJMP/10-Classic-Galapagos-The-Natural-Habitat-Experience.jpg",
    title: "Classic Galapagos: The Natural Habitat Experience",
    details: `Small-group adventures aboard your choice of private yachts, led by our outstanding naturalist guides. Snorkel and swim with sea lions, sea turtles and penguins on this incomparable nature odyssey.`,
    timeline: `8 or 10 Days / Year-Round, From $4995 (+air/permits)`,
    addon: true,
    additionalDetails: `NEW SHIP!`
  },
  { id: 4,
    image: "https://i.postimg.cc/L8pRY4Fn/48-Yellowstone-Wolf-Quest.jpg",
    title: "Yellowstone Wolf Quest Photo Adventure",
    details: `Passionate about wolves? Join us in the best place on the planet to search for them in the wild — and photograph an array of Yellowstone's iconic wildlife that shares this wild habitat with them.`,
    timeline: `7 Days / Mar, From $6495`,
    addon: false,
    additionalDetails: null
  },
  { id: 5,
    image: "https://i.postimg.cc/kgvCxr7w/36-The-Great-Alaskan-Grizzly-Encounter.jpg",
    title: "The Great Alaskan Grizzly Encounter",
    details: `An exclusive small-ship adventure to view the world's largest coastal grizzlies up close! Walk the shores as enormous brown bears dig for clams, forage for grasses and pursue salmon in tidal pools.`,
    timeline: `8 Days / Jun – Sep, From $8895`,
    addon: false,
    additionalDetails: null
  },
  { id: 6,
    image: "https://i.postimg.cc/mrZsjdD4/Botswana-Zimabwe-Explorer-repeater.jpg",
    title: "Secluded Botswana Safari",
    details: `Our flagship Botswana safari! A truly exclusive wilderness immersion in the Okavango Delta's best private wildlife reserves and beyond, plus Victoria Falls.`,
    timeline: `12 Days / May – Nov, From $11795 (+air)`,
    addon: false,
    additionalDetails: null
  },
  { id: 7,
    image: "https://i.postimg.cc/KzRySRBs/43-Discover-Greenland-The-Natural-Habitat-Experience.jpg",
    title: "Discover Greenland: The Natural Habitat Experience",
    details: `Encounter raw beauty and remote Arctic landscapes from our luxury expedition camp near the edge of the Greenland ice sheet. Explore by boat, kayak and on foot, where very few travelers ever venture.`,
    timeline: `9 Days / Jul – Sep, From $12995 (+air)`,
    addon: false,
    additionalDetails: null
  },
  { id: 8,
    image: "https://i.postimg.cc/xdsS4KJz/59-India-Tiger-Quest.jpg",
    title: "India Tiger Quest",
    details: `Deep within the jungles of Rajasthan, Ranthambore National Park offers some of India's best tiger viewing — and we take you there at the very best time of year to search for and photograph them!`,
    timeline: `7 Days / Apr – Jun, From $6995 (+air)`,
    addon: false,
    additionalDetails: null
  },
  { id: 9,
    image: "https://i.postimg.cc/mk9fkJdY/Justin-Gibson-Asia-Pacific-panda-tree-2880x1500.jpg",
    title: "The Wild Side of China: A Nature Odyssey",
    details: `Discover a side of China most travelers never see on our unique itinerary crafted to reveal rare panda habitat, diverse wildlife and Chinese nature at its most entrancing — including close-up panda encounters.`,
    timeline: `12 Days / Mar – May & Oct – Nov, From $11995`,
    addon: true,
    additionalDetails: "NEW ITINERARY!"
  },
  { id: 10,
    image: "https://i.postimg.cc/9FTCQRS6/30-31-Kenya-Migration-repater.jpg",
    title: "The Great Kenya Migration Safari",
    details: `Experience one of the world's most incredible wildlife events in Africa's most classic safari destination — Kenya, home to the massive movement of creatures that is the Great Migration!`,
    timeline: `8 Days / Jul – Sep, From $8995 (+air)`,
    addon: false,
    additionalDetails: null
  }
]
